import "./globals.css";
import { InViewContextProvider } from "./context/inView";

export const metadata = {
  title: "Shane Bergman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" type="text/css" href="../public/stlye.css" />
      </head>
      <body
        className={
          "bg-slate-900 leading-relaxed text-slate-400 antialiased selection:bg-teal-300 selection:text-teal-900"
        }
      >
        <InViewContextProvider>{children}</InViewContextProvider>
      </body>
    </html>
  );
}
